### PR TITLE
fix(tokens): updates border color to use color box

### LINKED ISSUE #74: Tokens > Border Colors: Hard to see colors
**Problem**
It's hard to see the tokens that we can use for *Border Colors* because it's showing the color in an itty bitty line. Similar colors are also shown next to each other.
Screen Shot 2019-08-28 at 11 00 20 AM

**Suggestion**
Show the border color _as a border_ by using the full height.
Screen Shot 2019-08-28 at 11 02 36 AM

**Example**
Salesforce Lightning System uses the full height to show the token for the border color - it's easy to see the colors that you can choose from.
Screen Shot 2019-08-28 at 11 06 40 AM

### PR DESCRIPTION
**Pull request by ItsMeWithTheFace**
Fixes #74. Transitioned to use of `ColorBox` (from `BorderBox`) to display Border Color examples, improving readability.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

File: packages/paste-types/src/style-props/backgroundColor.ts [hunk 1]
```diff
@@ -2,5 +2,5 @@ import {ThemeShape} from '@twilio-paste/theme-tokens';
 import {ResponsiveValue} from 'styled-system';
 
 export interface BackgroundColorProps {
-  backgroundColor?: ResponsiveValue<keyof ThemeShape['backgroundColors']>;
+  backgroundColor?: ResponsiveValue<keyof ThemeShape['backgroundColors']> | ResponsiveValue<keyof ThemeShape['borderColors']>;
```
Comment (TheSisb) [inline packages/paste-types/src/style-props/backgroundColor.ts]: So we don't want to make this change because this opens a huge can of worms where people can use borderColors for backgroundColors.  These types are going to be used to define everything, so this would break our system.

File: packages/paste-website/src/components/tokens-example/index.tsx [hunk 2]
```diff
@@ -17,10 +17,15 @@ export const ColorBox: React.FC<BackgroundColor> = ({backgroundColor}) => {
...
 };
 
-type BorderBoxProps = Pick<BoxProps, 'borderColor' | 'borderWidth'>;
-export const BorderBox: React.FC<BorderBoxProps> = ({borderColor, borderWidth}) => {
+type BorderBoxProps = Pick<BoxProps, 'borderColor' | 'borderWidth' | 'height'>;
+export const BorderBox: React.FC<BorderBoxProps> = ({borderColor, borderWidth, height}) => {
   return (
-    <Box borderStyle="solid none none none" borderColor={borderColor} borderWidth={borderWidth || 'borderWidth20'} />
+    <Box
+      borderStyle="solid none none none"
```
Comment (TheSisb) [inline packages/paste-website/src/components/tokens-example/index.tsx]: You have to adjust this style because right now it only renders the top border

File: packages/paste-website/src/components/tokens-example/index.tsx [hunk 3]
```diff
@@ -117,7 +122,7 @@ export const TokenExample: React.FC<TokenExampleProps> = ({token}) => {
     case 'color':
       return <ColorBox backgroundColor={token.value as any} />;
     case 'border-color':
-      return <ColorBox backgroundColor={tokenName as keyof ThemeShape['borderColors']} />;
+      return <BorderBox borderColor={tokenName as keyof ThemeShape['borderColors']} height='size60' />;
```
Comment (TheSisb) [inline packages/paste-website/src/components/tokens-example/index.tsx]: size60 is rather tall.  Have you checked the preview build? https://paste-git-fork-itsmewiththeface-tokens-border-color.twilio-dsys.now.sh/tokens

File: packages/paste-website/src/components/tokens-example/index.tsx [hunk 4]
```diff
@@ -17,10 +17,15 @@ export const ColorBox: React.FC<BackgroundColor> = ({backgroundColor}) => {
...
-export const BorderBox: React.FC<BorderBoxProps> = ({borderColor, borderWidth}) => {
+type BorderBoxProps = Pick<BoxProps, 'borderColor' | 'borderWidth' | 'height'>;
+export const BorderBox: React.FC<BorderBoxProps> = ({borderColor, borderWidth, height}) => {
   return (
-    <Box borderStyle="solid none none none" borderColor={borderColor} borderWidth={borderWidth || 'borderWidth20'} />
+    <Box
+      borderStyle="solid none none none"
+      borderColor={borderColor}
+      borderWidth={borderWidth || 'borderWidth20'}
+      height={height || undefined}
```
Comment (TheSisb) [inline packages/paste-website/src/components/tokens-example/index.tsx]: We should be able to just do `height={height}` here.

File: packages/paste-types/src/style-props/backgroundColor.ts (hunk 1 above)
Comment (ItsMeWithTheFace) [reply packages/paste-types/src/style-props/backgroundColor.ts]: Makes sense, thanks for the update

File: packages/paste-website/src/components/tokens-example/index.tsx (hunk 4 above)
Comment (ItsMeWithTheFace) [reply packages/paste-website/src/components/tokens-example/index.tsx]: Done

File: packages/paste-website/src/components/tokens-example/index.tsx (hunk 2 above)
Comment (ItsMeWithTheFace) [reply packages/paste-website/src/components/tokens-example/index.tsx]: Done

File: packages/paste-website/src/components/tokens-example/index.tsx [hunk 5]
```diff
@@ -17,10 +17,10 @@ export const ColorBox: React.FC<BackgroundColor> = ({backgroundColor}) => {
   return <Absolute backgroundColor={backgroundColor} padding="space50" preset="fill" />;
 };
 
-type BorderBoxProps = Pick<BoxProps, 'borderColor' | 'borderWidth'>;
-export const BorderBox: React.FC<BorderBoxProps> = ({borderColor, borderWidth}) => {
+type BorderBoxProps = Pick<BoxProps, 'borderColor' | 'borderWidth' | 'height'>;
```
Comment (TheSisb) [inline packages/paste-website/src/components/tokens-example/index.tsx]: I think we can simplify this further actually:
1- Remove this `| 'height'`
2- Remove `, height` on line 21
3- Remove `height={height}` on line 23
4- Add a hardcoded `padding="space60"` on line 23 (like how ShadowBox does on line 93, making the style consistent).

This has the added benefit of fixing border-widths too:
image

Comment (ItsMeWithTheFace) [reply packages/paste-website/src/components/tokens-example/index.tsx]: Sounds good!
